"""Cutting versions, and the changelog that falls out of them.

The file is generated rather than written, which is the whole point: a
changelog maintained by hand drifts from what shipped, and nobody notices
until they are reading it to find out when something broke. Generated from the
annotated tags, there is nowhere for it to drift from.

These tests run against this repository's real tags. That is deliberate - the
failure worth catching is a tag whose message the parser cannot read, and a
fixture would not have one.
"""

from __future__ import annotations

import os
import re
import sys

import pytest

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tools"))

import release


def test_the_version_scheme_bumps_the_right_number():
    assert release.next_version("v0.7.0", "minor") == "v0.8.0"
    assert release.next_version("v0.7.0", "patch") == "v0.7.1"
    assert release.next_version("v0.7.0", "major") == "v1.0.0"


def test_an_untagged_repo_starts_at_the_beginning():
    assert release.next_version(None, "minor") == "v0.1.0"


def test_a_patch_bump_does_not_reset_the_minor():
    assert release.next_version("v0.11.3", "patch") == "v0.11.4"


def test_versions_sort_numerically_not_lexically():
    """v0.10.0 is newer than v0.9.0, which string sorting gets backwards."""
    tags = [t for t, _, _, _ in release.released()]
    if "v0.10.0" in tags and "v0.9.0" in tags:
        assert tags.index("v0.10.0") < tags.index("v0.9.0")


def test_the_latest_tag_is_the_highest_not_the_last_made():
    """Tags were cut out of order when old landings were tagged late."""
    latest = release.latest_tag()
    tags = [t for t, _, _, _ in release.released()]
    assert latest == tags[0]


# --- reading the tags back ---------------------------------------------------


def test_every_release_parses():
    versions = release.released()
    assert versions, "this repo has version tags; reading them found none"
    for tag, date, headline, notes in versions:
        assert release.TAG_PATTERN.match(tag), tag
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", date), f"{tag}: {date!r}"
        assert headline, f"{tag} has no headline"


def test_the_headline_does_not_repeat_the_version():
    """Tag messages read 'v0.8.0 - name'; the version is already the heading."""
    for tag, _, headline, _ in release.released():
        assert not headline.startswith(tag), f"{tag}: {headline!r}"


def test_a_span_ending_before_head_is_respected():
    """--at is what let four landings that already shipped get their versions."""
    all_since = release.commits_since("v0.7.0", "HEAD")
    to_pivot = release.commits_since("v0.7.0", "v0.8.0")
    assert to_pivot, "v0.8.0 should contain commits after v0.7.0"
    assert len(to_pivot) < len(all_since)
    assert set(to_pivot) <= set(all_since)


# --- the generated file ------------------------------------------------------


def test_the_changelog_is_generated_from_the_tags(tmp_path):
    out = tmp_path / "CHANGELOG.md"
    assert release.write_changelog(str(out)) == 0
    text = out.read_text()
    for tag, _, headline, _ in release.released():
        assert f"## {tag} - {headline}" in text


def test_the_file_says_not_to_edit_it(tmp_path):
    """It is an output. Somebody will otherwise fix a typo into oblivion on
    the next run."""
    out = tmp_path / "CHANGELOG.md"
    release.write_changelog(str(out))
    assert "Do not edit this file by hand" in out.read_text()


def test_generating_it_twice_gives_the_same_file(tmp_path):
    """No timestamps, no ordering wobble - otherwise every run is a diff."""
    a, b = tmp_path / "a.md", tmp_path / "b.md"
    release.write_changelog(str(a))
    release.write_changelog(str(b))
    assert a.read_text() == b.read_text()


def test_the_newest_version_is_first(tmp_path):
    out = tmp_path / "CHANGELOG.md"
    release.write_changelog(str(out))
    text = out.read_text()
    tags = [t for t, _, _, _ in release.released()]
    positions = [text.index(f"## {t} ") for t in tags if f"## {t} " in text]
    assert positions == sorted(positions), "versions are out of order"


def test_the_checked_in_changelog_is_current():
    """Catches a release cut without refreshing the file."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "CHANGELOG.md")
    if not os.path.exists(path):
        pytest.skip("no CHANGELOG.md yet")
    latest = release.latest_tag()
    assert f"## {latest} " in open(path).read(), (
        f"{latest} is tagged but missing from CHANGELOG.md - "
        "run: .venv/bin/python tools/release.py --changelog"
    )
